version: 0.2
run-as: root
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g serverless@3.38.0
      - npm install
  build:
    commands:
      - serverless deploy --stage ${STAGE_NAME}
cache:
  paths:
    - node_modules
