// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "api AssetMgmt APIs",
    "version": "1"
  },
  "paths": {
    "/discovery": {
      "post": {
        "summary": "createDiscovery",
        "description": "",
        "operationId": "createDiscovery.post.discovery",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "accesstoken": [],
            "x-api-key": [],
            "Content-Type": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/createDiscoveryRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200 response",
            "schema": {
              "$ref": "#/definitions/getDiscoveryResponse"
            }
          }
        }
      }
    },
    "/discovery/{id}": {
      "patch": {
        "summary": "updateDiscovery",
        "description": "",
        "operationId": "updateDiscovery.patch.discovery/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "accesstoken": [],
            "x-api-key": [],
            "Content-Type": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/updateDiscoveryRequest"
            }
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response",
            "schema": {
              "$ref": "#/definitions/getDiscoveryResponse"
            }
          }
        }
      },
      "get": {
        "summary": "getDiscoveryDetails",
        "description": "",
        "operationId": "getDiscoveryDetails.get.discovery/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "accesstoken": [],
            "x-api-key": [],
            "Content-Type": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response",
            "schema": {
              "$ref": "#/definitions/getDiscoveryResponse"
            }
          }
        }
      },
      "delete": {
        "summary": "deleteDiscovery",
        "description": "",
        "operationId": "deleteDiscovery.delete.discovery/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "accesstoken": [],
            "x-api-key": [],
            "Content-Type": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response",
            "schema": {
              "$ref": "#/definitions/getDiscoveryResponse"
            }
          }
        }
      }
    },
    "/discoveries": {
      "get": {
        "summary": "getDiscoveryByCompany",
        "description": "",
        "operationId": "getDiscoveryByCompany.get.discoveries",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "accesstoken": [],
            "x-api-key": [],
            "Content-Type": []
          }
        ],
        "parameters": [
          {
            "in": "query",
            "name": "page",
            "type": "String",
            "description": "Filter by page number",
            "required": false
          },
          {
            "in": "query",
            "name": "size",
            "type": "String",
            "description": "Filter by page size",
            "required": false
          },
          {
            "in": "query",
            "name": "assetType",
            "type": "String",
            "description": "Filter by assetType",
            "required": false
          },
          {
            "in": "query",
            "name": "assetName",
            "type": "String",
            "description": "Filter by assetName",
            "required": false
          },
          {
            "in": "query",
            "name": "department",
            "type": "String",
            "description": "Filter by department",
            "required": false
          },
          {
            "in": "query",
            "name": "normalized",
            "type": "Boolean",
            "description": "Filter by department",
            "required": false
          }
        ],
        "responses": {
          "200": {
            "description": "200 response",
            "schema": {
              "$ref": "#/definitions/getDiscoveryListResponse"
            }
          }
        }
      }
    },
    "/normalization": {
      "post": {
        "summary": "createNormalization",
        "description": "",
        "operationId": "createNormalization.post.normalization",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "accesstoken": [],
            "x-api-key": [],
            "Content-Type": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/createNormalizationRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200 response",
            "schema": {
              "$ref": "#/definitions/getNormalizationResponse"
            }
          }
        }
      }
    },
    "/normalization/{id}": {
      "patch": {
        "summary": "updateNormalization",
        "description": "",
        "operationId": "updateNormalization.patch.normalization/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "accesstoken": [],
            "x-api-key": [],
            "Content-Type": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/updateNormalizationRequest"
            }
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response",
            "schema": {
              "$ref": "#/definitions/getNormalizationResponse"
            }
          }
        }
      },
      "get": {
        "summary": "getNormalizationDetails",
        "description": "",
        "operationId": "getNormalizationDetails.get.normalization/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "accesstoken": [],
            "x-api-key": [],
            "Content-Type": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response",
            "schema": {
              "$ref": "#/definitions/getNormalizationResponse"
            }
          }
        }
      },
      "delete": {
        "summary": "deleteNormalization",
        "description": "",
        "operationId": "deleteNormalization.delete.normalization/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "accesstoken": [],
            "x-api-key": [],
            "Content-Type": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response",
            "schema": {
              "$ref": "#/definitions/getDiscoveryResponse"
            }
          }
        }
      }
    },
    "/normalizations": {
      "get": {
        "summary": "getNormalizationByCompany",
        "description": "",
        "operationId": "getNormalizationByCompany.get.normalizations",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "accesstoken": [],
            "x-api-key": [],
            "Content-Type": []
          }
        ],
        "parameters": [
          {
            "in": "query",
            "name": "page",
            "type": "String",
            "description": "Filter by page number",
            "required": false
          },
          {
            "in": "query",
            "name": "size",
            "type": "String",
            "description": "Filter by page size",
            "required": false
          },
          {
            "in": "query",
            "name": "assetType",
            "type": "String",
            "description": "Filter by assetType",
            "required": false
          },
          {
            "in": "query",
            "name": "assetName",
            "type": "String",
            "description": "Filter by assetName",
            "required": false
          },
          {
            "in": "query",
            "name": "department",
            "type": "String",
            "description": "Filter by department",
            "required": false
          },
          {
            "in": "query",
            "name": "discovery",
            "type": "String",
            "description": "Filter by discovery",
            "required": false
          }
        ],
        "responses": {
          "200": {
            "description": "200 response",
            "schema": {
              "$ref": "#/definitions/getNormalizationListResponse"
            }
          }
        }
      }
    },
    "/template": {
      "post": {
        "summary": "createTemplate",
        "description": "",
        "operationId": "createTemplate.post.template",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "accesstoken": [],
            "x-api-key": [],
            "Content-Type": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/createTemplateRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200 response",
            "schema": {
              "$ref": "#/definitions/getTemplateResponse"
            }
          }
        }
      }
    },
    "/template/{id}": {
      "patch": {
        "summary": "updateTemplate",
        "description": "",
        "operationId": "updateTemplate.patch.template/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "accesstoken": [],
            "x-api-key": [],
            "Content-Type": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/createTemplateRequest"
            }
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response",
            "schema": {
              "$ref": "#/definitions/getTemplateResponse"
            }
          }
        }
      },
      "get": {
        "summary": "getTemplateDetails",
        "description": "",
        "operationId": "getTemplateDetails.get.template/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "accesstoken": [],
            "x-api-key": [],
            "Content-Type": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response",
            "schema": {
              "$ref": "#/definitions/getTemplateResponse"
            }
          }
        }
      },
      "delete": {
        "summary": "deleteTemplate",
        "description": "",
        "operationId": "deleteTemplate.delete.template/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "accesstoken": [],
            "x-api-key": [],
            "Content-Type": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response",
            "schema": {
              "$ref": "#/definitions/getTemplateResponse"
            }
          }
        }
      }
    },
    "/templates": {
      "get": {
        "summary": "getTemplateByCompany",
        "description": "",
        "operationId": "getTemplateByCompany.get.templates",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "accesstoken": [],
            "x-api-key": [],
            "Content-Type": []
          }
        ],
        "parameters": [
          {
            "in": "query",
            "name": "page",
            "type": "String",
            "description": "Filter by page number",
            "required": false
          },
          {
            "in": "query",
            "name": "size",
            "type": "String",
            "description": "Filter by page size",
            "required": false
          },
          {
            "in": "query",
            "name": "type",
            "type": "String",
            "description": "Filter by template Type",
            "required": false
          }
        ],
        "responses": {
          "200": {
            "description": "200 response",
            "schema": {
              "$ref": "#/definitions/getTemplateListResponse"
            }
          }
        }
      }
    },
    "/asset-type": {
      "post": {
        "summary": "createAssetType",
        "description": "",
        "operationId": "createAssetType.post.asset-type",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "accesstoken": [],
            "x-api-key": [],
            "Content-Type": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/createAssetTypeRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200 response",
            "schema": {
              "$ref": "#/definitions/getAssetTypeResponse"
            }
          }
        }
      }
    },
    "/asset-type/{id}": {
      "patch": {
        "summary": "updateAssetType",
        "description": "",
        "operationId": "updateAssetType.patch.asset-type/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "accesstoken": [],
            "x-api-key": [],
            "Content-Type": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/createAssetTypeRequest"
            }
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response",
            "schema": {
              "$ref": "#/definitions/getAssetTypeResponse"
            }
          }
        }
      },
      "get": {
        "summary": "getAssetTypeDetails",
        "description": "",
        "operationId": "getAssetTypeDetails.get.asset-type/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "accesstoken": [],
            "x-api-key": [],
            "Content-Type": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "in": "query",
            "name": "nodeId",
            "type": "String",
            "description": "Filter by node Id",
            "required": false
          }
        ],
        "responses": {
          "200": {
            "description": "200 response",
            "schema": {
              "$ref": "#/definitions/getAssetTypeResponse"
            }
          }
        }
      },
      "delete": {
        "summary": "deleteAssetType",
        "description": "",
        "operationId": "deleteAssetType.delete.asset-type/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "accesstoken": [],
            "x-api-key": [],
            "Content-Type": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "in": "query",
            "name": "nodeId",
            "type": "String",
            "description": "Filter by node Id",
            "required": false
          }
        ],
        "responses": {
          "200": {
            "description": "200 response",
            "schema": {
              "$ref": "#/definitions/getAssetTypeResponse"
            }
          }
        }
      }
    },
    "/asset-types": {
      "get": {
        "summary": "getAssetTypeByCompany",
        "description": "",
        "operationId": "getAssetTypeByCompany.get.asset-types",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "accesstoken": [],
            "x-api-key": [],
            "Content-Type": []
          }
        ],
        "parameters": [
          {
            "in": "query",
            "name": "page",
            "type": "String",
            "description": "Filter by page number",
            "required": false
          },
          {
            "in": "query",
            "name": "size",
            "type": "String",
            "description": "Filter by page size",
            "required": false
          },
          {
            "in": "query",
            "name": "searchName",
            "type": "String",
            "description": "Filter by name",
            "required": false
          }
        ],
        "responses": {
          "200": {
            "description": "200 response",
            "schema": {
              "$ref": "#/definitions/getAssetTypeListResponse"
            }
          }
        }
      }
    },
    "/asset": {
      "post": {
        "summary": "createAsset",
        "description": "",
        "operationId": "createAsset.post.asset",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "accesstoken": [],
            "x-api-key": [],
            "Content-Type": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/createAssetRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200 response",
            "schema": {
              "$ref": "#/definitions/getAssetResponse"
            }
          }
        }
      }
    },
    "/asset/{id}": {
      "patch": {
        "summary": "updateAsset",
        "description": "",
        "operationId": "updateAsset.patch.asset/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "accesstoken": [],
            "x-api-key": [],
            "Content-Type": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/createAssetRequest"
            }
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response",
            "schema": {
              "$ref": "#/definitions/getAssetResponse"
            }
          }
        }
      },
      "get": {
        "summary": "getAssetDetails",
        "description": "",
        "operationId": "getAssetDetails.get.asset/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "accesstoken": [],
            "x-api-key": [],
            "Content-Type": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "in": "query",
            "name": "nodeId",
            "type": "String",
            "description": "Filter by node Id",
            "required": false
          }
        ],
        "responses": {
          "200": {
            "description": "200 response",
            "schema": {
              "$ref": "#/definitions/getAssetResponse"
            }
          }
        }
      },
      "delete": {
        "summary": "deleteAsset",
        "description": "",
        "operationId": "deleteAsset.delete.asset/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "accesstoken": [],
            "x-api-key": [],
            "Content-Type": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "in": "query",
            "name": "nodeId",
            "type": "String",
            "description": "Filter by node Id",
            "required": false
          }
        ],
        "responses": {
          "200": {
            "description": "200 response",
            "schema": {
              "$ref": "#/definitions/getAssetResponse"
            }
          }
        }
      }
    },
    "/assets": {
      "get": {
        "summary": "getAssetByCompany",
        "description": "",
        "operationId": "getAssetByCompany.get.assets",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "accesstoken": [],
            "x-api-key": [],
            "Content-Type": []
          }
        ],
        "parameters": [
          {
            "in": "query",
            "name": "page",
            "type": "String",
            "description": "Filter by page number",
            "required": false
          },
          {
            "in": "query",
            "name": "size",
            "type": "String",
            "description": "Filter by page size",
            "required": false
          },
          {
            "in": "query",
            "name": "searchName",
            "type": "String",
            "description": "Filter by name",
            "required": false
          }
        ],
        "responses": {
          "200": {
            "description": "200 response",
            "schema": {
              "$ref": "#/definitions/getAssetListResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "getDiscoveryResponse": {
      "properties": {
        "_id": {
          "title": "getDiscoveryResponse._id",
          "type": "string"
        },
        "createdAt": {
          "title": "getDiscoveryResponse.createdAt",
          "type": "string"
        },
        "updatedAt": {
          "title": "getDiscoveryResponse.updatedAt",
          "type": "string"
        },
        "assetCode": {
          "title": "getDiscoveryResponse.assetCode",
          "type": "string"
        },
        "assetName": {
          "title": "getDiscoveryResponse.assetName",
          "type": "string"
        },
        "assetType": {
          "title": "getDiscoveryResponse.assetType",
          "type": "string"
        },
        "serialNumber": {
          "title": "getDiscoveryResponse.serialNumber",
          "type": "string"
        },
        "modelNumber": {
          "title": "getDiscoveryResponse.modelNumber",
          "type": "string"
        },
        "purchaseDate": {
          "title": "getDiscoveryResponse.purchaseDate",
          "type": "string"
        },
        "warrantyExpDate": {
          "title": "getDiscoveryResponse.warrantyExpDate",
          "type": "string"
        },
        "location": {
          "title": "getDiscoveryResponse.location",
          "type": "string"
        },
        "department": {
          "title": "getDiscoveryResponse.department",
          "type": "string"
        },
        "status": {
          "enum": [
            "ACTIVE",
            "IN_ACTIVE"
          ],
          "title": "getDiscoveryResponse.status",
          "type": "string"
        },
        "modelCategory": {
          "title": "getDiscoveryResponse.modelCategory",
          "type": "string"
        },
        "configurationItem": {
          "title": "getDiscoveryResponse.configurationItem",
          "type": "string"
        },
        "quantity": {
          "title": "getDiscoveryResponse.quantity",
          "type": "number"
        },
        "state": {
          "title": "getDiscoveryResponse.state",
          "type": "string"
        },
        "assignedTo": {
          "title": "getDiscoveryResponse.assignedTo",
          "type": "string"
        },
        "assignedDate": {
          "title": "getDiscoveryResponse.assignedDate",
          "type": "string"
        },
        "managedBy": {
          "title": "getDiscoveryResponse.managedBy",
          "type": "string"
        },
        "ownedBy": {
          "title": "getDiscoveryResponse.ownedBy",
          "type": "string"
        },
        "assetClass": {
          "title": "getDiscoveryResponse.assetClass",
          "type": "string"
        },
        "company": {
          "title": "getDiscoveryResponse.company",
          "type": "string"
        },
        "installedDate": {
          "title": "getDiscoveryResponse.installedDate",
          "type": "string"
        }
      },
      "required": [
        "_id",
        "createdAt",
        "updatedAt",
        "assetCode",
        "assetName",
        "assetType",
        "serialNumber",
        "modelNumber",
        "purchaseDate",
        "warrantyExpDate",
        "location",
        "department",
        "status"
      ],
      "additionalProperties": false,
      "title": "getDiscoveryResponse",
      "type": "object"
    },
    "getDiscoveryListResponse": {
      "properties": {
        "total": {
          "title": "getDiscoveryListResponse.total",
          "type": "number"
        },
        "items": {
          "items": {
            "$ref": "#/definitions/getDiscoveryResponse"
          },
          "title": "getDiscoveryListResponse.items",
          "type": "array"
        }
      },
      "required": [
        "total",
        "items"
      ],
      "additionalProperties": false,
      "title": "getDiscoveryListResponse",
      "type": "object"
    },
    "getTemplateResponse": {
      "properties": {
        "_id": {
          "title": "getTemplateResponse._id",
          "type": "string"
        },
        "createdAt": {
          "title": "getTemplateResponse.createdAt",
          "type": "string"
        },
        "updatedAt": {
          "title": "getTemplateResponse.updatedAt",
          "type": "string"
        },
        "type": {
          "title": "getTemplateResponse.type",
          "type": "string"
        },
        "name": {
          "title": "getTemplateResponse.name",
          "type": "string"
        },
        "tempData": {
          "additionalProperties": false,
          "title": "getTemplateResponse.tempData",
          "type": "object"
        },
        "status": {
          "title": "getTemplateResponse.status",
          "enum": [
            "ACTIVE | IN_ACTIVE"
          ],
          "type": "string"
        }
      },
      "required": [
        "_id",
        "createdAt",
        "updatedAt",
        "type",
        "name",
        "tempData",
        "status"
      ],
      "additionalProperties": false,
      "title": "getTemplateResponse",
      "type": "object"
    },
    "getTemplateListResponse": {
      "properties": {
        "total": {
          "title": "getTemplateListResponse.total",
          "type": "number"
        },
        "items": {
          "items": {
            "$ref": "#/definitions/getTemplateResponse"
          },
          "title": "getTemplateListResponse.items",
          "type": "array"
        }
      },
      "required": [
        "total",
        "items"
      ],
      "additionalProperties": false,
      "title": "getTemplateListResponse",
      "type": "object"
    },
    "getAssetTypeResponse": {
      "properties": {
        "_id": {
          "title": "getAssetTypeResponse._id",
          "type": "string"
        },
        "companyId": {
          "title": "getAssetTypeResponse.companyId",
          "type": "string"
        },
        "createdBy": {
          "title": "getAssetTypeResponse.createdBy",
          "type": "string"
        },
        "name": {
          "title": "getAssetTypeResponse.name",
          "type": "string"
        },
        "family": {
          "title": "getAssetTypeResponse.family",
          "type": "string"
        },
        "description": {
          "title": "getAssetTypeResponse.description",
          "type": "string"
        },
        "tags": {
          "items": {
            "title": "getAssetTypeResponse.tags.[]"
          },
          "title": "getAssetTypeResponse.tags",
          "type": "array"
        },
        "properties": {
          "items": {
            "additionalProperties": false,
            "type": "object"
          },
          "title": "getAssetTypeResponse.properties",
          "type": "array"
        },
        "templates": {
          "items": {
            "additionalProperties": false,
            "type": "object"
          },
          "title": "getAssetTypeResponse.templates",
          "type": "array"
        },
        "consumable": {
          "title": "getAssetTypeResponse.consumable",
          "type": "boolean"
        },
        "independently": {
          "title": "getAssetTypeResponse.independently",
          "type": "boolean"
        },
        "parentRequired": {
          "title": "getAssetTypeResponse.parentRequired",
          "type": "boolean"
        },
        "expiryDate": {
          "title": "getAssetTypeResponse.expiryDate",
          "type": "string"
        },
        "status": {
          "enum": [
            "ACTIVE",
            "IN_ACTIVE"
          ],
          "title": "getAssetTypeResponse.status",
          "type": "string"
        },
        "children": {
          "items": {
            "additionalProperties": false,
            "type": "object"
          },
          "title": "getAssetTypeResponse.children",
          "type": "array"
        },
        "createdAt": {
          "$ref": "#/definitions/Date",
          "title": "getAssetTypeResponse.createdAt"
        },
        "updatedAt": {
          "$ref": "#/definitions/Date",
          "title": "getAssetTypeResponse.updatedAt"
        }
      },
      "required": [
        "companyId",
        "createdBy",
        "status"
      ],
      "additionalProperties": false,
      "title": "getAssetTypeResponse",
      "type": "object"
    },
    "getAssetTypeListResponse": {
      "properties": {
        "total": {
          "title": "getAssetTypeListResponse.total",
          "type": "number"
        },
        "items": {
          "items": {
            "$ref": "#/definitions/getAssetTypeResponse"
          },
          "title": "getAssetTypeListResponse.items",
          "type": "array"
        }
      },
      "required": [
        "total",
        "items"
      ],
      "additionalProperties": false,
      "title": "getAssetTypeListResponse",
      "type": "object"
    },
    "getAssetResponse": {
      "properties": {
        "_id": {
          "title": "getAssetResponse._id",
          "type": "string"
        },
        "companyId": {
          "title": "getAssetResponse.companyId",
          "type": "string"
        },
        "createdBy": {
          "title": "getAssetResponse.createdBy",
          "type": "string"
        },
        "name": {
          "title": "getAssetResponse.name",
          "type": "string"
        },
        "assetDatas": {
          "items": {
            "properties": {
              "template": {
                "title": "template",
                "type": "string"
              },
              "templateData": {
                "additionalProperties": false,
                "title": "templateData",
                "type": "object"
              }
            },
            "required": [
              "template",
              "templateData"
            ],
            "additionalProperties": false,
            "type": "object"
          },
          "title": "getAssetResponse.assetDatas",
          "type": "array"
        },
        "createdAt": {
          "$ref": "#/definitions/Date",
          "title": "getAssetResponse.createdAt"
        },
        "updatedAt": {
          "$ref": "#/definitions/Date",
          "title": "getAssetResponse.updatedAt"
        }
      },
      "required": [
        "companyId",
        "createdBy",
        "assetDatas"
      ],
      "additionalProperties": false,
      "title": "getAssetResponse",
      "type": "object"
    },
    "getAssetListResponse": {
      "properties": {
        "total": {
          "title": "getAssetListResponse.total",
          "type": "number"
        },
        "items": {
          "items": {
            "$ref": "#/definitions/getAssetResponse"
          },
          "title": "getAssetListResponse.items",
          "type": "array"
        }
      },
      "required": [
        "total",
        "items"
      ],
      "additionalProperties": false,
      "title": "getAssetListResponse",
      "type": "object"
    },
    "createDiscoveryRequest": {
      "properties": {
        "items": {
          "items": {
            "properties": {
              "assetCode": {
                "title": "assetCode",
                "type": "string"
              },
              "assetName": {
                "title": "assetName",
                "type": "string"
              },
              "assetType": {
                "title": "assetType",
                "type": "string"
              },
              "serialNumber": {
                "title": "serialNumber",
                "type": "string"
              },
              "modelNumber": {
                "title": "modelNumber",
                "type": "string"
              },
              "purchaseDate": {
                "title": "purchaseDate",
                "type": "string"
              },
              "warrantyExpDate": {
                "title": "warrantyExpDate",
                "type": "string"
              },
              "location": {
                "title": "location",
                "type": "string"
              },
              "department": {
                "title": "department",
                "type": "string"
              },
              "status": {
                "enum": [
                  "ACTIVE",
                  "IN_ACTIVE"
                ],
                "title": "status",
                "type": "string"
              },
              "modelCategory": {
                "title": "modelCategory",
                "type": "string"
              },
              "configurationItem": {
                "title": "configurationItem",
                "type": "string"
              },
              "quantity": {
                "title": "quantity",
                "type": "number"
              },
              "state": {
                "title": "state",
                "type": "string"
              },
              "assignedTo": {
                "title": "assignedTo",
                "type": "string"
              },
              "assignedDate": {
                "title": "assignedDate",
                "type": "string"
              },
              "managedBy": {
                "title": "managedBy",
                "type": "string"
              },
              "ownedBy": {
                "title": "ownedBy",
                "type": "string"
              },
              "assetClass": {
                "title": "assetClass",
                "type": "string"
              },
              "company": {
                "title": "company",
                "type": "string"
              },
              "installedDate": {
                "title": "installedDate",
                "type": "string"
              }
            },
            "required": [
              "assetCode",
              "assetName",
              "assetType",
              "serialNumber",
              "modelNumber",
              "purchaseDate",
              "warrantyExpDate",
              "location",
              "department",
              "status"
            ],
            "additionalProperties": false,
            "type": "object"
          },
          "title": "createDiscoveryRequest.items",
          "type": "array"
        }
      },
      "required": [
        "items"
      ],
      "additionalProperties": false,
      "title": "createDiscoveryRequest",
      "type": "object"
    },
    "updateDiscoveryRequest": {
      "properties": {
        "assetName": {
          "title": "updateDiscoveryRequest.assetName",
          "type": "string"
        },
        "assetType": {
          "title": "updateDiscoveryRequest.assetType",
          "type": "string"
        },
        "serialNumber": {
          "title": "updateDiscoveryRequest.serialNumber",
          "type": "string"
        },
        "modelNumber": {
          "title": "updateDiscoveryRequest.modelNumber",
          "type": "string"
        },
        "purchaseDate": {
          "title": "updateDiscoveryRequest.purchaseDate",
          "type": "string"
        },
        "warrantyExpDate": {
          "title": "updateDiscoveryRequest.warrantyExpDate",
          "type": "string"
        },
        "location": {
          "title": "updateDiscoveryRequest.location",
          "type": "string"
        },
        "department": {
          "title": "updateDiscoveryRequest.department",
          "type": "string"
        },
        "status": {
          "title": "updateDiscoveryRequest.status",
          "enum": [
            "ACTIVE | IN_ACTIVE"
          ],
          "type": "string"
        }
      },
      "required": [
        "assetName",
        "assetType",
        "serialNumber",
        "modelNumber",
        "purchaseDate",
        "warrantyExpDate",
        "location",
        "department",
        "status"
      ],
      "additionalProperties": false,
      "title": "updateDiscoveryRequest",
      "type": "object"
    },
    "createTemplateRequest": {
      "properties": {
        "type": {
          "title": "createTemplateRequest.type",
          "enum": [
            "LOCATION_TEMP | WARRANTY_TEMP | MAINTAINANCE_TEMP | LEASE_TEMP | PURCHASE_TEMP | RENT_TEMP | FAMILY_TEMP"
          ],
          "type": "string"
        },
        "name": {
          "title": "createTemplateRequest.name",
          "type": "string"
        },
        "tempData": {
          "additionalProperties": false,
          "title": "createTemplateRequest.tempData",
          "type": "object"
        },
        "status": {
          "title": "createTemplateRequest.status",
          "enum": [
            "ACTIVE | IN_ACTIVE"
          ],
          "type": "string"
        }
      },
      "required": [
        "type",
        "name",
        "tempData",
        "status"
      ],
      "additionalProperties": false,
      "title": "createTemplateRequest",
      "type": "object"
    },
    "createAssetTypeRequest": {
      "properties": {
        "name": {
          "title": "createAssetTypeRequest.name",
          "type": "string"
        },
        "family": {
          "title": "createAssetTypeRequest.family",
          "type": "string"
        },
        "description": {
          "title": "createAssetTypeRequest.description",
          "type": "string"
        },
        "tags": {
          "items": {
            "title": "createAssetTypeRequest.tags.[]"
          },
          "title": "createAssetTypeRequest.tags",
          "type": "array"
        },
        "properties": {
          "items": {
            "title": "createAssetTypeRequest.properties.[]"
          },
          "title": "createAssetTypeRequest.properties",
          "type": "array"
        },
        "templates": {
          "items": {
            "title": "createAssetTypeRequest.templates.[]"
          },
          "title": "createAssetTypeRequest.templates",
          "type": "array"
        },
        "consumable": {
          "title": "createAssetTypeRequest.consumable",
          "type": "boolean"
        },
        "independently": {
          "title": "createAssetTypeRequest.independently",
          "type": "boolean"
        },
        "parentRequired": {
          "title": "createAssetTypeRequest.parentRequired",
          "type": "boolean"
        },
        "expiryDate": {
          "title": "createAssetTypeRequest.expiryDate",
          "type": "string"
        },
        "status": {
          "enum": [
            "ACTIVE",
            "IN_ACTIVE"
          ],
          "title": "createAssetTypeRequest.status",
          "type": "string"
        },
        "parentId": {
          "title": "createAssetTypeRequest.parentId",
          "type": "string"
        },
        "nodeParentId": {
          "title": "createAssetTypeRequest.nodeParentId",
          "type": "string"
        }
      },
      "required": [
        "status",
        "parentId",
        "nodeParentId"
      ],
      "additionalProperties": false,
      "title": "createAssetTypeRequest",
      "type": "object"
    },
    "createAssetRequest": {
      "properties": {
        "name": {
          "title": "createAssetRequest.name",
          "type": "string"
        },
        "assetType": {
          "title": "createAssetRequest.assetType",
          "type": "string"
        },
        "assetDatas": {
          "items": {
            "properties": {
              "template": {
                "title": "template",
                "type": "string"
              },
              "templateData": {
                "additionalProperties": false,
                "title": "templateData",
                "type": "object"
              }
            },
            "required": [
              "template",
              "templateData"
            ],
            "additionalProperties": false,
            "type": "object"
          },
          "title": "createAssetRequest.assetDatas",
          "type": "array"
        }
      },
      "required": [
        "assetType",
        "assetDatas"
      ],
      "additionalProperties": false,
      "title": "createAssetRequest",
      "type": "object"
    }
  },
  "securityDefinitions": {
    "accesstoken": {
      "type": "apiKey",
      "name": "accesstoken",
      "in": "header"
    },
    "x-api-key": {
      "type": "apiKey",
      "name": "x-api-key",
      "in": "header"
    },
    "Content-Type": {
      "type": "apiKey",
      "name": "Content-Type",
      "in": "header"
    }
  },
  "basePath": "/asset-mgmt",
  "host": "dev.api.apitestsuite.com",
  "schemes": [
    "https"
  ]
};